// This file is auto-generated by Supabase CLI.
// Run: npx supabase gen types typescript --linked > src/lib/supabase/types.ts
// after linking your project with: npx supabase link --project-ref <your-project-ref>

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          created_at: string
        }
        Insert: {
          id: string
          email?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          created_at?: string
        }
      }
      open_banking_tokens: {
        Row: {
          id: string
          user_id: string
          access_token: string
          refresh_token: string
          expires_at: string | null
          bank_account_no: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          access_token: string
          refresh_token: string
          expires_at?: string | null
          bank_account_no?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          access_token?: string
          refresh_token?: string
          expires_at?: string | null
          bank_account_no?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          user_id: string
          transaction_id: string
          amount: number
          currency: string
          exchange_rate: number | null
          krw_amount: number | null
          is_estimated_rate: boolean
          merchant_name: string | null
          category: string | null
          receipt_url: string | null
          transacted_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          transaction_id: string
          amount: number
          currency: string
          exchange_rate?: number | null
          krw_amount?: number | null
          is_estimated_rate?: boolean
          merchant_name?: string | null
          category?: string | null
          receipt_url?: string | null
          transacted_at: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          transaction_id?: string
          amount?: number
          currency?: string
          exchange_rate?: number | null
          krw_amount?: number | null
          is_estimated_rate?: boolean
          merchant_name?: string | null
          category?: string | null
          receipt_url?: string | null
          transacted_at?: string
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
